Fix Automate Git import if branch is symbolic ref
Branches can be symbolic refs, which need to be resolved to direct refs,
so that target is a commit.

Previously, some imports failed with error:

```
undefined method `time' for #<Rugged::Reference:0x...>
```

The problem appeared in release lasker-1.  Release kasparov-2 works as
expected.

Signed-off-by: Steffen Prohaska <prohaska@zib.de>