performance: do not load charts on missing metrics
When metrics are missing we should avoid to run charts-related functions
as they most likely fail. E.g.

  miq_chart_data = {"candu":null};

  TypeError: Cannot read property 'length' of null
    at load_jqplot_charts

This patch makes sure that we avoid to add any charts-related ajax (e.g
load_jqplot_charts) when data is missing in order to avoid failures and
complete the other required operations, e.g. miqSparkle(false)

Fixes #2987

Signed-off-by: Federico Simoncelli <fsimonce@redhat.com>