Require the hash extensions where we need fetch_path.
Fixes the following error when you run only part of the suite:
`bundle exec rspec spec/openstack`

```
  Failure/Error: OpenstackEventMonitor.new(opts).class.should eq
    OpenstackRabbitEventMonitor
  NoMethodError:
   undefined method `fetch_path' for {}:Hash
```