Do not use instance method from class method directly
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1343586

    [NameError]: undefined local variable or method `current_db_opts' for #<Class:0x0000000ce6fa30>
    in app/models/database_backup.rb:66:in `_gc'

Introduced by 929f11514cdfb8b80d172b626c62e8e523794227