target new refresh fails
When running publish vm workflow flow I saw:

[NoMethodError]: undefined method `base_class' for NilClass:Class  Method:[block in method_missing]
relationship_mixin.rb:621:in `block in remove_children'

and it is triggered from `save_ems_inventory_no_disconnect`. It means that `link_invenotry` do not
respects disconnect flag which is fixed by this patch.