This file doesn't exist and causes the build to fail
It is removed here https://github.com/ManageIQ/manageiq-pods/blame/df663933ff91b5bf59da7efeae601f31e47fac80/images/manageiq-webserver-worker/Dockerfile#L18

Error:
mv: cannot stat '/etc/httpd/conf.d/ssl.conf': No such file or directory
Error: error building at STEP "RUN source /etc/default/evm &&     $APPLIANCE_SOURCE_DIRECTORY/setup &&     mv /etc/httpd/conf.d/ssl.conf{,.orig} &&     echo "# This file intentionally left blank. ManageIQ maintains its own SSL configuration" > /etc/httpd/conf.d/ssl.conf": error while running runtime: exit status 1