Walk Object subclasses and avoid delegator classes
BasicObject objects do not have class defined.  This was leading to the following error after enabling ruby object logging
on azure and amazon refresh workers:

ERROR: An unhandled error has occurred: undefined method `class' for #<BasicObject:0x00007fdc61f154d8>.

Additionally, some classes that do delegation, such as proxies could respond to `class` but not in the way we expect.  They could
be using method_missing and respond_to_missing?.

We only want to class Object subclasses that have `class` defined.