Fix DescendantLoader for ActsAsArModel
Alternate implementation to #8818

The prior fix failed when calling `ChargebackVm.superclass` because it created a circular dependency...

Before:
```
[1] pry(main)> ChargebackVm.superclass
RuntimeError: Circular dependency detected while autoloading constant ChargebackVm
from /Users/jfrey/.gem/ruby/2.2.4/bundler/gems/rails-3d01d00e348f/activesupport/lib/active_support/dependencies.rb:509:in `load_missing_constant'
```

After:
```
[1] pry(main)> ChargebackVm.superclass
=> Chargeback
```