We assert root_disk_size_by_flavor commonly so define it there
See 66317eb26b and f148a0cab1

Fixes a few openstack test failures such as:

```
  1) ManageIQ::Providers::Openstack::CloudManager::Refresher will perform a full refresh against RHOS
     Failure/Error: assert_common
     NoMethodError:
       undefined method `root_disk_size_by_flavor' for #<RSpec::Core::ExampleGroup::Nested_1:0x007fdc0772b650>
     # ./spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb:241:in `block in assert_flavors'
     # ./spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb:226:in `assert_flavors'
     # ./spec/models/manageiq/providers/openstack/cloud_manager/refresh_spec_common.rb:43:in `assert_common'
     # ./spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_icehouse_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_icehouse_spec.rb:13:in `times'
     # ./spec/models/manageiq/providers/openstack/cloud_manager/refresher_rhos_icehouse_spec.rb:13:in `block (2 levels) in <top (required)>'
```