Use fetch_path to handle the case where :ws_values is nil.
When :ws_values is nil, CustomizationTemplate.substitute_erb throws out [NoMethodError]: undefined method `[]' for nil:NilClass.

https://bugzilla.redhat.com/show_bug.cgi?id=1436194